# Generated by Django 4.1.2 on 2024-07-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id_navbar', models.AutoField(db_column='idNavbar', primary_key=True, serialize=False)),
                ('navbar', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
