# Generated by Django 4.1.2 on 2024-07-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
