# Generated by Django 4.1.2 on 2024-07-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0002_navbar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
