# Generated by Django 4.1.2 on 2024-07-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0003_alter_navbar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_navbar', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('img_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
    ]
