# Generated by Django 4.1.2 on 2024-07-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0004_servicios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
