# Generated by Django 4.1.2 on 2024-08-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0005_rename_servicios_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(db_column='idProyecto', primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(blank=True, max_length=50, null=True)),
                ('img_proyecto', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
