# Generated by Django 4.1.2 on 2024-08-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0006_proyecto_alter_servicio_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(db_column='idContacto', primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
